import { prisma } from '../prisma.js';
import { config } from '../config.js';

/**
 * Ensures the configured default doctor row exists (used when doctorId is omitted in API calls).
 */
export async function ensureDefaultDoctor() {
  const id = config.defaultDoctorId;
  await prisma.doctor.upsert({
    where: { id },
    update: {},
    create: { id, name: 'General Clinic', specialization: null },
  });
  return id;
}

export async function listDoctors() {
  await ensureDefaultDoctor();
  return prisma.doctor.findMany({ orderBy: { name: 'asc' } });
}

/**
 * Resolves doctor id from client input. Empty or missing means default doctor.
 */
export async function resolveDoctorId(doctorId) {
  await ensureDefaultDoctor();
  if (doctorId == null || String(doctorId).trim() === '') {
    return config.defaultDoctorId;
  }
  const id = String(doctorId).trim();
  const d = await prisma.doctor.findUnique({ where: { id } });
  if (!d) {
    const err = new Error('Unknown doctor');
    err.statusCode = 400;
    throw err;
  }
  return id;
}

/**
 * Create a new doctor (room). ID is generated by Prisma (cuid).
 */
export async function createDoctor({ name, specialization }) {
  await ensureDefaultDoctor();
  const n = String(name ?? '').trim();
  if (!n) {
    const err = new Error('name is required');
    err.statusCode = 400;
    throw err;
  }
  const specRaw = specialization != null ? String(specialization).trim() : '';
  const spec = specRaw === '' ? null : specRaw;
  return prisma.doctor.create({
    data: { name: n, specialization: spec },
  });
}

/**
 * Update display name and/or specialization.
 */
export async function updateDoctor(doctorId, { name, specialization }) {
  await ensureDefaultDoctor();
  const id = String(doctorId ?? '').trim();
  if (!id) {
    const err = new Error('doctor id is required');
    err.statusCode = 400;
    throw err;
  }
  const existing = await prisma.doctor.findUnique({ where: { id } });
  if (!existing) {
    const err = new Error('Doctor not found');
    err.statusCode = 404;
    throw err;
  }
  const data = {};
  if (name !== undefined) {
    const n = String(name).trim();
    if (!n) {
      const err = new Error('name cannot be empty');
      err.statusCode = 400;
      throw err;
    }
    data.name = n;
  }
  if (specialization !== undefined) {
    const s = specialization != null ? String(specialization).trim() : '';
    data.specialization = s === '' ? null : s;
  }
  if (Object.keys(data).length === 0) {
    return existing;
  }
  return prisma.doctor.update({ where: { id }, data });
}

/**
 * Remove a doctor row. Blocked for the configured default doctor and if any queue rows reference this doctor.
 * Visit rows get doctorId cleared (Prisma onDelete: SetNull) once queues are gone.
 */
export async function deleteDoctor(doctorId) {
  await ensureDefaultDoctor();
  const id = String(doctorId ?? '').trim();
  if (!id) {
    const err = new Error('doctor id is required');
    err.statusCode = 400;
    throw err;
  }
  if (id === config.defaultDoctorId) {
    const err = new Error('Cannot delete the default clinic doctor');
    err.statusCode = 400;
    throw err;
  }
  const existing = await prisma.doctor.findUnique({ where: { id } });
  if (!existing) {
    const err = new Error('Doctor not found');
    err.statusCode = 404;
    throw err;
  }
  const qCount = await prisma.queue.count({ where: { doctorId: id } });
  if (qCount > 0) {
    const err = new Error(
      `Cannot delete: ${qCount} queue row(s) are still linked to this doctor (including completed visits). Remove is only possible for doctors who have never had queue activity, or use Prisma Studio for advanced cleanup.`
    );
    err.statusCode = 409;
    throw err;
  }
  await prisma.doctor.delete({ where: { id } });
  return { ok: true, id };
}
